### PR TITLE
Fixes to the CI and the test suite

### PR DESCRIPTION
**Pull request by maximlt**

### CODE REVIEW

**Comment by Hoxbro** [comment]
Was wondering if windows could be fixed by setting system environment variable 'MAMBA_NO_BANNER=1'

**Comment by Hoxbro** [comment]
Was wondering if windows could be fixed by setting system environment variable 'MAMBA_NO_BANNER=1'

**Comment by maximlt** [comment]
> Was wondering if windows could be fixed by setting system environment variable ‘MAMBA_NO_BANNER=1’

Thanks for the setting to remove the banner, it's annoyed me for a while (it's huge!). It didn't fix the issue though (https://github.com/pyviz-dev/pyctdev/issues/90) and I had to use a (rather ugly) hack to get the tests to run on Windows. It'll have to be removed at some point anyway, so a real fix (to pyctdev?) needs to be found.

> I don’t know why ‘datashader/tests/test_datatypes.py::TestRaggedGetitem::test_getitem_invalid’ fails on CI as it passed on my system.

Yes it's weird. In the end I've just chosen to skip the failing test, thanks anyway for your previous PR @Hoxbro, you did 95% of the work!

**Comment by jbednar** [comment]
Thanks, @Hoxbro and @maximlt for all your debugging and all the resulting fixes! This has been quite a slog!

**Pull request merged**
