### PR TITLE
Fix half-pixel offset error in Polygon rasterization

### PR DESCRIPTION
**Pull request by jonmmease**
Closes https://github.com/holoviz/datashader/issues/852

Subtract a half-pixel offset when mapping vertex coords to into canvas space. This way the scanline algorithm is checking whether the center of each pixel is in the polygon, rather than the lower left corner.

```python
import datashader as ds
from spatialpandas import GeoDataFrame, GeoSeries
from spatialpandas.geometry import Polygon

p1 = Polygon([[0, 0, 2, 0, 1, 1, 0, 0]])
p2 = Polygon([[0, 0, 1, 1, 0, 1, 0, 0]])

gdf = GeoDataFrame({'geometry': GeoSeries([p1, p2])})

cvs = ds.Canvas(plot_width=5, plot_height=5)

cvs.polygons(gdf, geometry='geometry')
```
```
<xarray.DataArray (y: 5, x: 5)>
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])
Coordinates:
  * x        (x) float64 0.2 0.6 1.0 1.4 1.8
  * y        (y) float64 0.1 0.3 0.5 0.7 0.9
```

cc @philippjfr

### CODE REVIEW

**Comment by jbednar** [comment]
It would be great to see the same fix for https://github.com/holoviz/datashader/issues/806 :-)

**Comment by philippjfr** [comment]
Looks good, thanks for the quick fix. Seems like there's a flake. np.nan imported but unused in test_polygons.py.

**Comment by jonmmease** [comment]
@philippfr thanks! I can push the flake fix in an hour or so, but feel free to push to the branch if you want.

@jbednar yeah, that does look like the same kind of issue.  I’m not nearly as familiar with the Trimesh logic though, so I don’t want to make that change in this PR.  But I can take a look at it next time i’m working in that codepath.

**Comment by jbednar** [comment]
Thanks!

**Pull request merged**
