### PR TITLE
unpin Numba

### PR DESCRIPTION
**Pull request by esc**
Numba was  pinned due to:

https://github.com/numba/numba/issues/5570

But this issue has been resolved with Numba 0.49.1 -- so this should fix
that.

### CODE REVIEW

**Comment by esc** [comment]
Appveyor seems to report:

```
doit test_all
.  test_all
.\examples\filetimes.py:77:15: F522 '...'.format(...) has unused named argument(s): flush
.\examples\filetimes.py:319:15: F522 '...'.format(...) has unused named argument(s): flush
.\examples\filetimes.py:328:15: F522 '...'.format(...) has unused named argument(s): flush
.\examples\filetimes.py:337:15: F522 '...'.format(...) has unused named argument(s): flush
.\examples\filetimes.py:340:15: F522 '...'.format(...) has unused named argument(s): flush
.\examples\filetimes.py:344:15: F522 '...'.format(...) has unused named argument(s): flush
TaskFailed - taskid:test_all
Command failed: 'flake8  && pytest "--nbsmoke-lint" "-k" ".ipynb" && pytest "--nbsmoke-verify" "-k" ".ipynb" && pytest "datashader" && datashader "fetch-data" "--path=examples" "--use-test-data" && pytest "--nbsmoke-run" "-k" ".ipynb"' returned 1
```

**Comment by esc** [comment]
The appveyor errors are new from `flake8 3.8.1` which isn't yet available from anaconda.org

**Comment by esc** [comment]
So I fixed the flake8 errors on Appveyor and am now getting:

```
========== 696 passed, 59 skipped, 38 warnings in 429.28s (0:07:09) ===========
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test\Scripts\datashader-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 3252, in <module>
    @_call_aside
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\pkg_resources\__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'imagecodecs>=2020.2.18' distribution was not found and is required by tifffile
TaskFailed - taskid:test_all
Command failed: 'flake8  && pytest "--nbsmoke-lint" "-k" ".ipynb" && pytest "--nbsmoke-verify" "-k" ".ipynb" && pytest "datashader" && datashader "fetch-data" "--path=examples" "--use-test-data" && pytest "--nbsmoke-run" "-k" ".ipynb"' returned 1
```

**Comment by philippjfr** [comment]
Looks good. Ready to merge?

**Comment by esc** [comment]
@philippjfr fire in the hole!

**Comment by philippjfr** [comment]
Thanks!

**Pull request merged**
