### PR TITLE
Geopandas example

### PR DESCRIPTION
**Pull request by ianthomas23**
This adds a new page to the User Guide in the docs to show use of GeoPandas. It uses one of the `geodatasets` and shows three images, one of which is (population density per US county in 1990):

Screenshot 2023-10-25 at 15 16 44

It is minimalistic at this stage as it uses pure Datashader. When we have support in HoloViews for this, we can add an interactive section to the end and hence show interactive zooming and panning, and show colorbars as well, to make it more interesting.

### CODE REVIEW

**Review by jbednar — APPROVED** [review]
Looks good! Can you include a sentence or two in the new notebook about the tradeoffs between GeoPandas and SpatialPandas? Presumably something about one being faster, but the other being more convenient if you are already have your data in GeoPandas?

**Comment by jbednar** [comment]
Looks good, thanks! I forget -- do we have antialiasing supported for polygons? If so it would be good to add that to the example.

**Comment by ianthomas23** [comment]
> Looks good, thanks! I forget -- do we have antialiasing supported for polygons?

No, there is only antialiasing support for lines.

**Comment by jbednar** [comment]
Oops; I wasn't clear. I meant, antialiasing for polygon _outlines_.  Those are just polylines, so I'd think they should be supported?

**Comment by ianthomas23** [comment]
> Oops; I wasn't clear. I meant, antialiasing for polygon _outlines_. Those are just polylines, so I'd think they should be supported?

Yes, any use of `Canvas.line()` supports antialiasing regardless of the type of the `source`. Here it is with `line_width=2`:

Screenshot 2023-10-26 at 08 56 09

**Pull request merged**
